---
- name: Avi Controller | Services | init.d | Set container env for non-systemd
  set_fact:
    con_env_variables_extras: "{{ con_env_variables_extras + ['NON_SYSTEMD=1'] }}"

- block:
    - name: Avi Controller | Services | init.d | Deploy the avicontroller service
      template: src=16.x/avicontroller.j2 dest=/etc/init.d/avicontroller mode=0755
      register: avicontroller_service_16
      notify: Avi Controller | Services | init.d | Restart the avicontroller_watcher service
    - set_fact: avicontroller_service={{ avicontroller_service_16 }}
  when: not con_new_service

- block:
    - name: Avi Controller | Services | init.d | Deploy the avicontroller service | New Service
      copy: src=init/avicontroller dest=/etc/init.d/avicontroller mode=0755
      register: avicontroller_service_17
      notify: Avi Controller | Services | init.d | Restart the avicontroller_watcher service
    - set_fact: avicontroller_service={{ avicontroller_service_16 }}
  when: con_new_service

- name: Avi Controller | Services | init.d | Deploy the avicontroller_watcher.sh script
  copy: src=init/avicontroller_watcher.sh dest=/etc/init.d/avicontroller_watcher.sh mode=0755
  register: avicontroller_watcher_sh

- name: Avi Controller | Services | init.d | Deploy the avicontroller_watcher service
  copy: src=init/avicontroller_watcher dest=/etc/init.d/avicontroller_watcher mode=0755
  register: avicontroller_watcher_service
  notify: Avi Controller | Services | init.d | Restart the avicontroller_watcher service

- name: Avi Controller | Services | init.d | Deploying avicontroller_watcher rc links
  file: src=/etc/init.d/avicontroller_watcher dest={{ item }} state=link
  with_items:
    - /etc/rc0.d/K99avicontroller_watcher
    - /etc/rc1.d/K99avicontroller_watcher
    - /etc/rc2.d/S99avicontroller_watcher
    - /etc/rc3.d/S99avicontroller_watcher
    - /etc/rc4.d/S99avicontroller_watcher
    - /etc/rc5.d/S99avicontroller_watcher
    - /etc/rc6.d/K99avicontroller_watcher
